[phases.install]
cmds = ["npm install --workspaces --include-workspace-root"]

[phases.build]
cmds = [
  "npm --workspace backend run prisma:generate",
  "npm run build"
]

[start]
cmd = "npm --workspace backend run prisma:deploy && npm --workspace backend run prisma:seed && npm start"
